config/routes.rb
Rails.application.routes.draw do
  # Override the params accepted in the User Registration
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :users, only: [:update] do
    resources :favorites, only: [:create, :destroy]
    resources :participations, only: [ :index, :create, :destroy ]
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :organizations, only: [ :index, :show, :new, :create, :edit, :update, :destroy] do
    resources :admins, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :posts
    resources :events
  end

  get '/feed', to: 'pages#feed'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="media-links">
    <ul>
      <li>
        <div class="link-container">
          <a href=""><i class="fab fa-facebook-f"></i></a>
        </div>
      </li>
      <li>
        <div class="link-container">
          <a href=""><i class="fab fa-instagram"></i></a>
        </div>
      </li>
      <li>
        <div class="link-container">
          <a href=""><i class="fab fa-twitter"></i></a>
        </div>
      </li>
    </ul>
  </div>
  <div class="other-links">
    <div class="link">
      <p>ABOUT US</p>
    </div>
     <div class="link">
      <p>|</p>
    </div>
    <div class="link">
      <p>CONTACTS</p>
    </div>
     <div class="link">
      <p>|</p>
    </div>
    <div class="link">
      <p>BLOG</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light fixed-top">
    <%#= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag('logo.png', width: "160") %>
    <% #end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-core" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-core">
      <ul class="navbar-nav ml-lg-auto">

        <li class="nav-item">
        <%= link_to "Organizations", organizations_path, class: "nav-link" %>
        </li>

      <% #if user_signed_in? %>
        <li id="nav-btn-box" class="nav-item">
        <%#= link_to "About Us", about_path, class: "nav-btn" %>
        </li>
        <br>
        <li class="nav-item dropdown">
              <% #if current_user.photo.attached? %>
                <%#= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% #else %>
                <%#= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <%# end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%#= link_to " #{current_user.first_name.capitalize }'s Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Add an Organization", new_organization_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
        </li>
      <% #else %>
        <li class="nav-item login">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li id="nav-btn-box" class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </li>
      <%# end %>
      </ul>
    </div>
</div>

app/views/shared/_navbar1.html.erb
<div class="nav">
  <div class="logo">
    <%= link_to image_tag('logo.png', width: "160"), root_path %>
  </div>
  <div class="nav-links-container">
    <ul class="nav-links">
      <li>
        <a href=""><%= link_to "Home", root_path %></a>
      </li>
      <li>
        <a href=""><%= link_to "Organizations", organizations_path %></a>
      </li>
     </ul>
     <ul class="nav-login">
      <% def new_user_session_path
           # code here
         end
         def new_user_registration_path
           # code here
         end
         def destroy_user_session_path
           # code here
         end
         if current_user.present? %>
        <li class="nav-avatar">
          <%= avatar_small(current_user) %>
            <ul class="avatar-links">
              <li>
                <a href=""><%= link_to "My Account", feed_path %></a>
              </li>
              <li>
                <a href=""><%= link_to "Log out", destroy_user_session_path, method: :delete %></a>
              </li>
            </ul>
        </li>
      <% else %>
        <li>
          <a href=""><%= link_to "Log in", new_user_session_path %></a>
        </li>
        <li>
          <a href=""><%= link_to "Sign Up", new_user_registration_path %></a>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="burger">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="line3"></div>
  </div>
</div>