config/routes.rb
Rails.application.routes.draw do
  # Override the params accepted in the User Registration
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :users, only: [:update] do
    resources :favorites, only: [:create, :destroy]
    resources :participations, only: [ :index, :create, :destroy ]
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :organizations, only: [ :index, :show, :new, :create, :edit, :update, :destroy] do
    resources :admins, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :posts
    resources :events
  end

  get '/feed', to: 'pages#feed'
end

app/models/organization.rb
class Organization < ApplicationRecord
  # Schema relationships
  has_many :admins
  has_many :events
  has_many :favourites
  has_many :posts, dependent: :destroy

  has_many_attached :photos
  has_one_attached :avatar

  belongs_to :category

  # Model validations
  validates :name,          presence: true, length: { minimum: 2 }
  validates :address,       presence: true, length: { minimum: 2 }
  validates :city,          presence: true, length: { minimum: 2 }
  validates :phone_number,  presence: true, length: { minimum: 9 }
  validates :email,         presence: true, length: { minimum: 2 } # Missing the Regex validation
  validates :description,   presence: true, length: { minimum: 5 }

  # Get the Organization's coordinates based on the address and city provided by the user
  geocoded_by :full_address
  after_validation :geocode, if: :will_save_change_to_address?

  # Get the city, zip_code and country based on the coordinates
  reverse_geocoded_by :latitude, :longitude do |organization, results|
    if geo = results.first
      organization.city     = geo.city
      organization.zip_code = geo.postal_code
      organization.country  = geo.country
    end
  end
  after_validation :reverse_geocode

  # Creates a more complete adress from the input provide by the user
  # Only meant to be used in Portugal
  def full_address
    [address, city, "Portugal"].compact.join(', ')
  end

  # Gets the user that is the Organization's admin
  # There's a single admin per Organization
  def find_admin(user)
    current_user_admin = admins.find { |admin| admin.user_id == user.id }
    return current_user_admin
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    # If the user searches for something: it will display the organizations in a 30km radius;
    # else: all organizations will be displayed
    @organizations = policy_scope(Organization)
    if params[:query].present?
      @organizations = Organization.near(params[:query], 30)
      @organizations = policy_scope(Organization)
    else
      @organizations = Organization.all
    end
    @selected_organizations = @organizations.order('created_at ASC').first(9)
  end

  def show
    @organization = Organization.find(params[:id])
    authorize @organization
  end

  def new
    @organization = Organization.new
    authorize @organization
  end

  def create
    @organization = Organization.new(organization_params)
    authorize @organization

    @organization.save!
    @admin = Admin.new
    @admin.user_id = current_user.id
    @admin.organization_id = @organization.id
    @admin.can_edit = true
    @admin.can_add_events = true
    @admin.can_add_posts = true
    @admin.can_add_admin = true
    @admin.is_owner = true

    @admin.save!
    redirect_to organization_path(@organization)
  end

  def edit
    @organization = Organization.find(params[:id])
    authorize @organization
  end

  def update
    @organization = Organization.find(params[:id])
    authorize @organization
    @organization.update(organization_params)
    redirect_to organization_path(@organization)
  end

  def destroy
    authorize @organization
    @organization.destroy
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :address, :phone_number, :email, :category_id, :description, :city, :zip_code, :country, :avatar, photos: [])
  end
end

app/views/organizations/_about_organization.html.erb
<div class="container-fluid p-5">
	<h5><%= @organization.description%></h5>
</div>

app/views/organizations/_form_organization.html.erb
<div class="container p-5 mt-5">
  <div class="row">
    <div class="col-lg-10">
      <%= simple_form_for organization do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.association :category, label_method: :name %>
        <%= f.input :phone_number %>
        <%= f.input :email %>
        <%= f.input :address %>
        <%= f.input :city %>
        <%= f.input :avatar, as: :file %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.button :submit, class: "form-btn" %>
      <% end %>
    </div>
  </div>  
</div>

app/views/organizations/_participate_event.html.erb
<div class="modal" id="participate_event" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <% @organization.events.each do |event| %>
          <%= event.title %>
          <%end%>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Confirm your participation in this event</p>
      </div>
      <div class="modal-footer">
        <input class="btn btn-info" type="submit" value="Submit">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/organizations/edit.html.erb
 <%= render "form_organization", organization: @organization %>

app/views/organizations/index.html.erb
<div class="container-fluid p-0">
	<div class="jumbotron jumbotron-fluid">
		<div class="container">
			<h1 class="display-4"><i class="fas fa-map-marker-alt"></i>Members</h1>
			<p class="lead">This page includes profiles for nonprofits. This is free to members subscribed as an organisation.</p>
		</div>
	</div>
</div>



<div class="container">
	<div class="row">
		<% @selected_organizations.each do |organization| %>
			<div class="col-lg-4 col-md-6 col-sm-10 col-10">
				<a class="card1">
					<% if organization.photos.attached? %>
						<%= cl_image_tag organization.photos[0].key, class: "card-img-top" %>
					<%end%>		
					<h3><%= organization.name.upcase %></h3>
					<p class="small"><%= truncate(organization.description, :length => 60) %></p>
					<div class="go-corner">
						<div class="go-arrow">
							→ 
						</div>
					</div>
				</a>
				<%= link_to "Read More", organization_path(organization),  class: "button-card-org" %>
			</div>
		<% end %>	
	</div>
</div>

app/views/organizations/new.html.erb
 <%= render "form_organization", organization: @organization %>

app/views/organizations/show.html.erb
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
        <h1 class="font-weight-light"><i class="fas fa-map-marker-alt"></i><%= @organization.name.upcase%></h1>
        <p class="lead"><%= @organization.address.capitalize%></p>
      </div>
    </div>
  </div>
</header>

<!--SideBar-->
<div class="wrapper d-flex align-items-stretch">
  <nav id="sidebar">
    <div class="p-4 pt-5">
      <%= cl_image_tag @organization.photos[0].key, class: "img-jumb-show-page" %>
      <ul class="list-unstyled components mb-5">
        <li class="active">
          <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
          <ul class="collapse list-unstyled" id="homeSubmenu">
            <li>
              <% if !current_user.nil? && current_user.can_edit?(@organization)%>
                <%= link_to (fa_icon "edit", class: 'mx-1', size: '1x', color: 'white' ), edit_organization_path(@organization.id) %>
              <% end %>
            </li>
            <li>
              <% if !current_user.nil? && current_user.can_add_posts_for?(@organization) %>
                <%= link_to "Add a new post", new_organization_post_path(@organization.id) %>
              <% end %>
            </li>
            <li>
              <% if !current_user.nil? && current_user.can_add_events_for?(@organization)%>
                <%= link_to "Add a new event", new_organization_event_path(@organization.id) %>
              <% end %>
            </li>
            <li>
              <% if !current_user.nil? && current_user.can_add_admin_to?(@organization)%>
                <%= link_to "Add a new admin", new_organization_admin_path(@organization.id) %>
              <% end %>
            </li>
          </ul>
        </li>
        <li>
            <a href="#">About</a>
        </li>
        <li>
          <a href="#posts-show-page">Posts</a>
        </li>
        <li>
          <a href="#events-show-page">Events</a>
        </li>
      </ul>
      <div class="last">
			  <p class="small"><%= link_to "<-- Back to all organizations", organizations_path(@organizations), {:style=>'color:#FFFFFF;', :hover=>'font-weight:bold;'}%></p>
      </div>
    </div>
  </nav>

  <!-- Page Content  -->
  <div id="content" class="p-4 p-md-5">
    <div class="container-fluid">
      <button type="button" id="sidebarCollapse" class="btn btn-primary">
        <i class="fa fa-bars"></i>
        <span class="sr-only">Toggle Menu</span>
      </button>
      <%= render "about_organization", organization: @organization %>
      <div class="container-fluid p-5">
        <h2 id="posts-show-page"class="text-center posts-showpage">Posts</h2>      
        <% @organization.posts.each do |post|%>
          <% if !post.nil?%>
            <h4><%= post.title %><h4>
            <h6>What will happen: <%= post.description %></h6>
            <h6>Location: <%= post.location %></h6>
            <h6>Date: <%= post.date.strftime("%d %B %Y") %></h6>
          <% end %>
        <% end %>  
      </div>
      <div class="container-fluid p-5">
        <h2 id="events-show-page"class="text-center events-showpage">Events</h2>
        <%@organization.events.each do |event|%>
          <% if !event.nil?%>
            <h4><%= event.title %><h4>
            <h6>What will happen: <%= event.description %></h6>
            <h6>People Needed: <%= event.part_count %></h6>
            <h6>Location: <%= event.location %></h6>
            <h6>Date: <%= event.date.strftime("%d %B %Y") %></h6>
            <% if current_user.nil? %>
              <%= link_to "Participate", new_user_session_path %>
              <% else %>
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#participate_event">Participate</button>
            <% end %>  
          <% end %>
        <% end %>
      </div>  
    </div>
	</div>
</div>

<%= render "participate_event", event: @event %>